name: Checks Lint with Ruff

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ruff
        run: pip install ruff==0.8.4

      - name: Make script executable
        run: chmod +x ./scripts/start_ruffs_check.sh

      - name: Run Ruff linter
        run: ./scripts/start_ruffs_check.sh
