name: Checks Lint with Ruff

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make sure script is executable
        run: chmod +x ./scripts/start_ruffs.sh

      - name: Run Ruff linter
        run: ./scripts/start_ruffs.sh
